# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildboard_app', '0003_auto_20160921_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='division',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
