# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildboard_app', '0004_company_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set([('name', 'division')]),
        ),
    ]
