# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildboard_app', '0005_auto_20160922_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='narrative',
            new_name='product_narrative',
        ),
    ]
