version: '2'

volumes:
  postgres_data:
  postgres_backup: {}


services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - postgres_backup:/backups
    env_file: .env
  django:
    restart: always
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    command: /gunicorn.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file: .env
  
  nginx:
    build: ./compose/nginx
    depends_on: 
      - django
      - certbot
    environment:
      - MY_DOMAIN_NAME=buildboard.cornelltech.io
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

  certbot:
    image: quay.io/letsencrypt/letsencrypt
    command: bash -c "sleep 6 && certbot certonly -n --standalone -d buildboard.cornelltech.io --text --agree-tos --email jc2855@cornell.edu --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --keep-until-expiring --standalone-supported-challenges http-01"
    entrypoint: ""
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "80"
      - "443"
    environment:
      - TERM=xterm


