# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildboard_app', '0002_auto_20160921_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_photo',
            field=models.ImageField(default=1, upload_to='uploads/team-photos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='one_liner',
            field=models.TextField(max_length=250, unique=True),
        ),
    ]
