# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildboard_app', '0003_auto_20160809_2342'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set([('semester_type', 'year')]),
        ),
    ]
