# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildboard_app', '0004_auto_20160809_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_type',
            field=models.CharField(choices=[('FALL', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer')], default='FALL', max_length=20),
        ),
    ]
