# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildboard_app', '0005_auto_20160809_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='semester_studio_description',
            field=models.CharField(default='Cornell Tech Company Challenges inspire integrated teams of computer science, business, and information science Masters students to deliver new business ideas and prototypes in response to challenges posed by leading startups, companies, and nonprofits.', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='semester_studio_title',
            field=models.CharField(default='Product Studio', max_length=50),
            preserve_default=False,
        ),
    ]
