# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildboard_app', '0006_auto_20160810_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='narrative',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='one_liner',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_studio_description',
            field=models.TextField(max_length=250),
        ),
    ]
