# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildboard_app', '0008_auto_20160810_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ('year', '-semester_type')},
        ),
    ]
