# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildboard_app', '0009_auto_20160810_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='/static/uploads/logo/'),
        ),
    ]
