# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildboard_app', '0013_auto_20160810_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250)),
                ('description', models.TextField(max_length=500)),
                ('url', models.URLField()),
                ('projects', models.ManyToManyField(to='buildboard_app.Project')),
            ],
        ),
    ]
