# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 19:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildboard_app', '0014_studioview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-last_modified']},
        ),
        migrations.AddField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 16, 19, 22, 7, 394959)),
            preserve_default=False,
        ),
    ]
