# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('buildboard_app', '0015_auto_20160816_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='inviter',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='project',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(to='accounts.Account'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
