# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildboard_app', '0016_auto_20160824_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studioview',
            name='url',
        ),
        migrations.AddField(
            model_name='studioview',
            name='url_identifier',
            field=models.URLField(default='test', unique=True),
            preserve_default=False,
        ),
    ]
