# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildboard_app', '0017_auto_20160914_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studioview',
            name='url_identifier',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
