# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildboard_app', '0018_auto_20160914_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='url_key',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
