# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildboard_app', '0019_semester_url_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ('-year', '-semester_type')},
        ),
    ]
