# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildboard_app', '0020_auto_20160915_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='uploads/logo/'),
        ),
    ]
