# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildboard_app', '0021_auto_20160915_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
