# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 04:02
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('accounts', '0004_auto_20160922_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedUser',
            fields=[
            ],
            options={
                'ordering': ['first_name', 'last_name'],
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.OrderedUser'),
        ),
    ]
