# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160922_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
    ]
